"""Third extraction route (issue #71): native-text-layer PDF -> Markdown,
same two-step pipeline as `pdf_text_generic.py` (issue #68) but with a
per-document filtering spec **generated by a Bedrock LLM**, instead of no
spec at all (generic-only) or a hand-written one (issue #59, the 10
`case-1-carolina-mmgd/` PDFs).

## What the LLM does and does not do

The LLM never rewrites, summarizes or reorders a single character of the
document. Its only output is a filtering *spec* — the same JSON shape
issue #59 wrote by hand under
`hackathon/tools/prototypes/pdf_to_markdown/specs/*.json` (`drop_pages`,
`drop_line_literals`, `drop_line_contains`, `strip_trailing_rubric_tokens`,
`notes`) — which `filter_verbatim.filter_lines`/`main()` (issue #59) then
applies exactly the same way it applies a hand-written spec: it only ever
*deletes* lines/pages that match a rule; everything else is copied through
byte for byte from `pdftotext -layout`'s own output. This is what keeps the
"cópia verbatim, nunca paráfrase" guarantee (D14) true *by construction*,
regardless of anything the LLM decides: a bug in the LLM's judgment can
cause it to under-remove (leave boilerplate in) or over-remove (drop a page
it shouldn't have) — both are visible, auditable mistakes in the spec JSON
— but it can never cause a paraphrase, because the only operation available
to the spec is deletion.

## Why an LLM call and not more hand-written regexes

`pdf_text_generic.py`'s built-in regexes (`filter_verbatim.LINE_DROP_PATTERNS`
etc.) already remove the boilerplate that repeats near-identically across
*every* document in the corpus (SICNET/SEI signature/certification
footers). What is left over — and what issue #59's hand-written specs show
— is genuinely *per-document*: a reviewer's rubric initials repeated on
every page, a company-specific letterhead/address footer, an ICP-Brasil
digital-signature stamp `pdftotext -layout` garbles differently depending
on the PDF's own column layout, or (rare, not seen in the 10 case-1 PDFs)
a whole embedded attachment. Writing one more generic regex per document
family does not scale to the corpus's ~2682 documents; an LLM reading the
same per-page raw text a human reviewer would read, and emitting the same
kind of spec, does.

## Model choice (acceptance criterion 1)

Both `us.anthropic.claude-haiku-4-5-20251001-v1:0` and `us.anthropic.claude-sonnet-5`
were confirmed to invoke successfully via Bedrock's `Converse` API in
`us-east-1` on this account (see the issue #71 evidence pack for the raw
probe output: model id, region, `usage.inputTokens`/`outputTokens`, no
credentials logged). Both were then piloted on the richest of the 10
case-1 PDFs (`recurso-48500.000639-2019-07.pdf`, the one issue #59's own
spec required all four spec fields for) with the exact prompt below,
side by side. Haiku 4.5's output was materially as good as Sonnet 5's —
same signature/footer/certificate lines identified, same conservative
`drop_pages: []` decision — at roughly 1/3 the per-document cost (Haiku
4.5: $1.00/$5.00 per MTok in/out; Sonnet 5: $2.00/$10.00 per MTok, Anthropic
published rates, used here as the Bedrock on-demand cost basis — see
`PRICING_USD_PER_MILLION_TOKENS` below and the evidence pack's cost table).
Per issue #71's own instruction ("preferir o mais barato que passe no
piloto"), **Haiku 4.5 is `DEFAULT_MODEL_ID`**; `PdfLlmSpecRoute` still takes
`model_id` as a constructor argument so a future run can swap in Sonnet 5
for a document family where Haiku's judgment turns out to be insufficient,
without touching this module's code.

## The prompt (auditable, not just "ask an LLM")

`SYSTEM_PROMPT` below is the full instruction sent on every call. Notable
design choices, all present because an earlier, looser version of this
prompt was piloted against the same richest case-1 PDF and produced a
worse spec (see the evidence pack for the side-by-side):

- It tells the model exactly which boilerplate the generic filter already
  removes, so the model does not waste output tokens (= cost) re-deriving
  rules that already exist, and does not risk double-specifying a rule in
  a way that conflicts with the generic one.
- `drop_pages` is deliberately the most restrictive field, with an explicit
  allow-list (a full "Relatório de Vistoria"/"Laudo Técnico", or a
  "Contrato Social") and an explicit warning **not** to treat the source
  system's own `(ANEXO: NNN)` corner-stamp label as a removal signal — that
  label is SICNET/SEI's generic word for "an attached file in this
  process", used for the Exposição de Motivos and Razões de Recurso just as
  much as for a genuine third-party letter (see
  `hackathon/tools/prototypes/pdf_to_markdown/README.md`, "Where the AC's
  line lives"). An early pilot without this warning had Sonnet 5 drop two
  genuinely-labelled-`(ANEXO: 001)` pages of `recurso-48500.000639-2019-07.pdf`
  that are a third-party letter reproduced as evidence, not a vistoria
  report/laudo técnico/contrato social — exactly the over-removal this
  warning exists to prevent.
- A dedicated paragraph tells the model that "identificação de quem
  assinou" also applies to a signature block *inside* correspondence kept
  as evidence (an embedded email/letter), not only to the document's own
  primary signer — because issue #59's manual spec for this same PDF
  removes exactly that (the two embedded correspondents' closing signature
  blocks on pages 24-26), while keeping the email routing headers and
  message bodies verbatim.
- `notes` is required even when every list is empty, forcing the model to
  state it actually reviewed the document rather than defaulting silently.

## Remaining, documented differences from the 10 manual specs (#59)

Piloting the final prompt above against all 10 case-1 PDFs (see the
evidence pack) found the LLM-generated specs produce Markdown that is
**line-for-line identical or a strict superset** of the manually-filtered
Markdown for 9 of the 10 documents (the LLM leaves a small number of extra
boilerplate/signature lines in place that the manual spec removed — never
the reverse; no case of the LLM removing real content the manual spec
kept). The one documented exception is
`recurso-48500.000639-2019-07.pdf`: both Haiku 4.5 and Sonnet 5, even with
the embedded-correspondence-signature paragraph above, chose *not* to
remove the two embedded correspondents' closing signature blocks (page 24's
garbled "Ronaldo de Oliveira" line and the letterhead/footer lines next to
it; pages 25-26's "Emerson da Silva Ribeiro"/"Ronaldo de Oliveira" email
closings) that the manual spec does remove — Sonnet 5's own `notes` explain
why: the page-24 text is visibly OCR-garbled (a known, documented
extraction-quality limitation, see the prototype README's "Known
limitation" section) and the model judged an exact-literal-match rule
against garbled text too risky to specify safely, preferring to leave a
few extra signature-identification lines in rather than risk a wrong match
against degraded text. This is a legitimate, explained difference in
judgment, not a defect: it makes the LLM route strictly more conservative
(never drops real content) at the cost of a handful of leftover
signature-identification lines on one page of one of the 10 documents.

## Two-tier cache: executor cache vs. this route's own spec cache

The executor's cache (`executor.py`, keyed by `(sha256, extractor_version)`)
decides whether `extract()` is called *at all* for a given document — a
cache hit there never reaches this module. `extractor_version` is a fixed
string per deployment of this route (bumped only when the *code* — prompt
text, filter logic, model default — changes in a way that would change
every document's output), so bumping it invalidates the whole corpus's
cache at once, which is correct for a code change but wrong for "I want to
regenerate just one document's LLM-generated spec".

That per-document regeneration is what this module's own spec cache is
for (acceptance criterion: "regerar uma spec invalida o cache só daquele
documento"). It is content-addressed, not version-addressed: the cache key
is `sha256(raw_pdftotext_output) + PROMPT_VERSION + model_id`
(`_spec_cache_key`), stored as one JSON file per document under
`<output_dir>/llm_specs/<key>.json` (a sibling of the executor's own
`markdown/`/`cache/` directories — derived from `out_path.parent.parent`,
since a route is never given `output_dir` directly per the extraction-route
contract). Regenerating one document's spec is: delete that one file (and,
so the executor actually calls `extract()` again, that document's own
executor cache entry, `<output_dir>/cache/<sha256>__<extractor_version>.json`
— also content-addressed by `sha256`, so removing it never touches any
other document). Both caches only ever key by content, never by a global
version counter that would force the whole corpus to redo LLM calls (and
re-spend money) for a change scoped to one document.
"""

from __future__ import annotations

import hashlib
import json
import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Protocol

from . import ExtractionResult
from .pdf_text_generic import MIN_CHARS_PER_PAGE, _extract_raw_text, _filter_verbatim

EXTRACTOR_VERSION = "pdf_llm_spec@1"
PROMPT_VERSION = "pdf_llm_spec_prompt@1"

REGION = "us-east-1"
DEFAULT_MODEL_ID = "us.anthropic.claude-haiku-4-5-20251001-v1:0"

# Anthropic's published per-token rates (USD per 1,000,000 tokens), used
# here as the Bedrock on-demand cost basis for the estimate this route
# logs per document (see module docstring, "Model choice"). If the
# workshop's actual Bedrock bill differs, that is a pricing-table
# discrepancy to reconcile against AWS Cost Explorer, not a bug in this
# module's arithmetic.
PRICING_USD_PER_MILLION_TOKENS = {
    "us.anthropic.claude-haiku-4-5-20251001-v1:0": {"input": 1.00, "output": 5.00},
    "us.anthropic.claude-sonnet-5": {"input": 2.00, "output": 10.00},
}

SPEC_TOOL_NAME = "emitir_spec_filtragem"

SPEC_TOOL_SCHEMA = {
    "toolSpec": {
        "name": SPEC_TOOL_NAME,
        "description": "Emite a especificação de remoção verbatim para este documento.",
        "inputSchema": {
            "json": {
                "type": "object",
                "properties": {
                    "drop_pages": {
                        "type": "array",
                        "items": {"type": "integer"},
                        "description": (
                            "Páginas inteiras a descartar — só relatório de "
                            "vistoria/laudo técnico completo ou contrato social."
                        ),
                    },
                    "drop_line_literals": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Linhas a remover por casamento exato (após strip).",
                    },
                    "drop_line_contains": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Substrings que, se presentes numa linha, a removem.",
                    },
                    "strip_trailing_rubric_tokens": {
                        "type": "array",
                        "items": {"type": "string"},
                        "description": "Tokens a remover apenas do final de uma linha.",
                    },
                    "notes": {
                        "type": "string",
                        "description": "Justificativa de cada regra proposta (obrigatório).",
                    },
                },
                "required": [
                    "drop_pages",
                    "drop_line_literals",
                    "drop_line_contains",
                    "strip_trailing_rubric_tokens",
                    "notes",
                ],
            }
        },
    }
}

SYSTEM_PROMPT = """Você decide o que REMOVER do texto bruto de um PDF oficial da ANEEL, extraído mecanicamente por pdftotext -layout, página por página (marcadores "<!-- pdftotext:page N -->").

Você NUNCA reescreve, resume ou parafraseia nada. Sua única saída é uma especificação de remoção (JSON), aplicada por um programa determinístico que apenas deleta linhas/páginas que casam exatamente com o que você especificar — o resto do texto é copiado byte a byte, incluindo erros de OCR/layout.

Um filtro genérico JÁ remove automaticamente, em todo documento, sem você precisar listar:
- "Documento assinado digitalmente." e "Consulte a autenticidade deste documento em http://sicnet2.aneel.gov.br/...";
- "Documento assinado digitalmente por <nome>, em <data> às <hora>";
- "(Assinado digitalmente)"/"(Assinatura digital)" seguido do nome/cargo do signatário (até 3 linhas);
- o parágrafo SEI "Documento assinado eletronicamente por ..." + parágrafo de autenticidade + linha "Referência: Processo nº ...";
- o carimbo de número de processo/protocolo quando é a primeira linha não-vazia da página;
- o rodapé "<carimbo> SEI <processo> / pg. N" repetido em toda página;
- o rodapé antigo "Pág. N da Exposição de Motivos ...".

Sua tarefa é encontrar o que é ESPECÍFICO deste documento e ainda sobra, usando 5 campos:

1. drop_pages (MUITO RESTRITIVO — use raramente): páginas inteiras a descartar. Só se aplica quando a página é, ela mesma, um dos três tipos abaixo, com fronteira clara (cabeçalho/título próprio diferente do documento principal):
   (a) um "Relatório de Vistoria" ou "Laudo Técnico" completo (relatório de inspeção/engenharia, com seções técnicas próprias: objetivo, metodologia, constatações);
   (b) um "Contrato Social" (ato constitutivo de empresa, registrado em Junta Comercial);
   (c) nada além disso.
   NÃO use drop_pages para: cartas/ofícios/e-mails de terceiros citados como prova ou precedente (mesmo que sobre outro assunto ou processo, mesmo com outro signatário) — esses ficam; o rótulo do sistema "(ANEXO: NNN)" no canto da página NÃO é sinal de nada — é a numeração interna do SICNET/SEI para qualquer arquivo do processo, inclusive a própria Exposição de Motivos, Razões de Recurso, Votos e a correspondência citada como prova. Na dúvida, NÃO remova a página — prefira sempre manter o conteúdo e remover só a assinatura/rubrica com os outros 3 campos.

2. drop_line_literals: uma linha específica repetida neste documento (rubrica/iniciais de revisor, um carimbo de certificado digital ICP-Brasil garbled, uma linha de rodapé de endereço/telefone/e-mail institucional) — cópia EXATA (após strip) da linha.

3. drop_line_contains: um SUBSTRING de uma linha garbled (carimbo de assinatura digital multi-coluna que o pdftotext espalha/mistura com o texto ao redor, com espaçamento irregular entre letras) — só quando não dá para casar a linha inteira por drop_line_literals.

4. strip_trailing_rubric_tokens: um token curto (iniciais) que aparece sempre no FINAL de uma linha de conteúdo real (ex.: endereço) e deve ser removido do final da linha, mantendo o resto da linha.

5. notes (obrigatório): texto justificando CADA regra proposta — por que existe, o que remove, por que não é conteúdo principal. Se as 4 listas vierem vazias, diga isso explicitamente e confirme que revisou o documento e não achou nada específico além do filtro genérico.

Nunca remova: rótulos de formulário (ex. "NOME:", "CARGO/FUNÇÃO:", "ASSINATURA:"), corpo de e-mails/cartas reproduzidos como prova ou precedente, ou qualquer conteúdo argumentativo/legal/técnico — só identificação de quem assinou, rubricas de revisor, carimbos de certificado digital, e (raramente) anexos completos do tipo (a)/(b) acima.

IMPORTANTE — assinaturas dentro de correspondência reproduzida como prova: quando uma página reproduz uma carta ou e-mail de terceiros como prova/precedente (algo que você decidiu manter, não é um anexo do tipo (a)/(b)), a regra de "identificação de quem assinou" AINDA se aplica ao encerramento dessa carta/e-mail — mantenha o corpo da mensagem (texto, datas, valores, argumentos) e os cabeçalhos de roteamento de e-mail (De/Para/Cc/Assunto/Enviado em) INTEGRALMENTE, mas remova o bloco de assinatura de encerramento de quem escreveu (nome completo, cargo, departamento, empresa, telefone, e-mail pessoal, site) — trate como identificação de quem assinou, mesmo não sendo o signatário principal do documento. Se o texto dessa assinatura estiver visivelmente degradado/garbled pelo OCR/layout a ponto de um casamento literal ser arriscado, é aceitável deixá-la — documente essa decisão em notes.
"""


@dataclass
class SpecGenerationResult:
    spec: dict
    model_id: str
    region: str
    input_tokens: int
    output_tokens: int


class SpecGenerationError(Exception):
    """Raised when the LLM call fails or returns a spec that fails
    validation — the route's caller decides the fallback (see
    `PdfLlmSpecRoute.extract`)."""


class GenerateFn(Protocol):
    def __call__(self, raw_text: str) -> SpecGenerationResult: ...


def estimate_cost_usd(model_id: str, input_tokens: int, output_tokens: int) -> float | None:
    pricing = PRICING_USD_PER_MILLION_TOKENS.get(model_id)
    if pricing is None:
        return None
    return (input_tokens * pricing["input"] + output_tokens * pricing["output"]) / 1_000_000


def _validate_spec(spec: dict) -> dict:
    """Defensive validation of the LLM's tool-call input — never trust it
    blindly. Raises `SpecGenerationError` on any shape mismatch; the caller
    falls back to the generic-only filter rather than applying a malformed
    spec."""
    if not isinstance(spec, dict):
        raise SpecGenerationError(f"spec não é um objeto JSON: {spec!r}")

    def _list_of_str(key: str) -> list[str]:
        value = spec.get(key, [])
        if not isinstance(value, list) or not all(isinstance(item, str) for item in value):
            raise SpecGenerationError(f"campo {key!r} não é uma lista de strings: {value!r}")
        return value

    drop_pages = spec.get("drop_pages", [])
    if not isinstance(drop_pages, list) or not all(isinstance(item, int) for item in drop_pages):
        raise SpecGenerationError(f"campo drop_pages não é uma lista de inteiros: {drop_pages!r}")

    notes = spec.get("notes")
    if not isinstance(notes, str) or not notes.strip():
        raise SpecGenerationError(f"campo notes ausente ou vazio: {notes!r}")

    return {
        "drop_pages": drop_pages,
        "drop_line_literals": _list_of_str("drop_line_literals"),
        "drop_line_contains": _list_of_str("drop_line_contains"),
        "strip_trailing_rubric_tokens": _list_of_str("strip_trailing_rubric_tokens"),
        "notes": notes,
    }


def make_bedrock_generate_fn(model_id: str = DEFAULT_MODEL_ID, region: str = REGION) -> GenerateFn:
    """Builds a `GenerateFn` backed by a real Bedrock `Converse` call —
    the production path. Tests inject their own fake `GenerateFn` instead
    (see `test_routes_pdf_llm_spec.py`) so they never depend on real
    credentials or spend real money."""
    import boto3

    client = boto3.client("bedrock-runtime", region_name=region)

    def generate(raw_text: str) -> SpecGenerationResult:
        line_count = raw_text.count("\n")
        response = client.converse(
            modelId=model_id,
            system=[{"text": SYSTEM_PROMPT}],
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"text": f"Texto bruto (pdftotext -layout, {line_count} linhas):\n\n{raw_text}"}
                    ],
                }
            ],
            toolConfig={
                "tools": [SPEC_TOOL_SCHEMA],
                "toolChoice": {"tool": {"name": SPEC_TOOL_NAME}},
            },
            inferenceConfig={"maxTokens": 4096},
        )
        usage = response["usage"]
        tool_input = None
        for block in response["output"]["message"]["content"]:
            if "toolUse" in block:
                tool_input = block["toolUse"]["input"]
                break
        if tool_input is None:
            raise SpecGenerationError(
                f"resposta do Bedrock não contém toolUse (stopReason={response.get('stopReason')!r})"
            )
        spec = _validate_spec(tool_input)
        return SpecGenerationResult(
            spec=spec,
            model_id=model_id,
            region=region,
            input_tokens=usage["inputTokens"],
            output_tokens=usage["outputTokens"],
        )

    return generate


def _spec_cache_key(raw_text: str, model_id: str) -> str:
    digest = hashlib.sha256()
    digest.update(raw_text.encode("utf-8"))
    digest.update(b"|")
    digest.update(PROMPT_VERSION.encode("utf-8"))
    digest.update(b"|")
    digest.update(model_id.encode("utf-8"))
    return digest.hexdigest()


class PdfLlmSpecRoute:
    """See module docstring for the full design rationale. Registered
    *before* `PdfTextGenericRoute` in `cli.py::build_registry()` — both
    claim `formato == "pdf"`, and `RouteRegistry.dispatch` picks the first
    match, so this route is the one every PDF actually reaches; the
    fallback to generic-only filtering happens *inside* `extract()`
    (below), never by falling through to a second registered route."""

    name = "pdf_llm_spec"
    extractor_version = EXTRACTOR_VERSION

    def __init__(
        self,
        model_id: str = DEFAULT_MODEL_ID,
        region: str = REGION,
        generate_fn: GenerateFn | None = None,
        spec_cache_dir: Path | None = None,
    ):
        self.model_id = model_id
        self.region = region
        self._generate_fn = generate_fn
        self._spec_cache_dir_override = spec_cache_dir

    def can_handle(self, formato: str | None) -> bool:
        return formato == "pdf"

    def extract(self, source_path: Path, out_path: Path) -> ExtractionResult:
        try:
            page_count = _extract_raw_text.count_pages(source_path)
        except Exception as exc:
            return ExtractionResult(
                status="error",
                extractor_version=self.extractor_version,
                route=self.name,
                message=f"pdfinfo falhou: {exc}",
            )

        if page_count == 0:
            return ExtractionResult(
                status="error",
                extractor_version=self.extractor_version,
                route=self.name,
                message="pdfinfo reportou 0 páginas",
            )

        pages_text: list[str] = []
        for page in range(1, page_count + 1):
            try:
                pages_text.append(_extract_raw_text.extract_page(source_path, page))
            except Exception as exc:
                return ExtractionResult(
                    status="error",
                    extractor_version=self.extractor_version,
                    route=self.name,
                    message=f"pdftotext falhou na página {page}: {exc}",
                )

        total_chars = sum(len(re.sub(r"\s", "", text)) for text in pages_text)
        if total_chars / page_count < MIN_CHARS_PER_PAGE:
            # No usable text layer — not an LLM-spec question at all, same
            # heuristic and same fallback destination as pdf_text_generic.py.
            return ExtractionResult(
                status="pending",
                extractor_version=self.extractor_version,
                route=self.name,
                pages_total=page_count,
                message=(
                    "sem camada de texto extraível (media de "
                    f"{total_chars / page_count:.1f} caracteres/página) — "
                    "candidato à rota de OCR (#72)"
                ),
            )

        raw_lines: list[str] = []
        for page_no, text in enumerate(pages_text, start=1):
            raw_lines.append(f"<!-- pdftotext:page {page_no} -->")
            raw_lines.extend(text.split("\n"))
        raw_text = "\n".join(raw_lines)

        spec, spec_message = self._get_or_generate_spec(raw_text, out_path)

        drop_pages = set(spec.get("drop_pages", []))
        drop_line_literals = frozenset(spec.get("drop_line_literals", []))
        drop_line_contains = tuple(spec.get("drop_line_contains", []))
        strip_trailing_rubric_tokens = tuple(spec.get("strip_trailing_rubric_tokens", []))

        pages = _filter_verbatim.split_pages(raw_text)
        kept_lines: list[str] = []
        raw_line_count = 0
        pages_dropped_whole = 0
        for page_no, page_lines in pages:
            raw_line_count += len(page_lines)
            if page_no in drop_pages:
                pages_dropped_whole += 1
                continue
            kept_lines.append(f"<!-- page:{page_no} -->")
            page_lines = _filter_verbatim.drop_first_line_protocol_stamp(page_lines)
            kept_lines.extend(
                _filter_verbatim.filter_lines(
                    page_lines, drop_line_literals, drop_line_contains, strip_trailing_rubric_tokens
                )
            )
            kept_lines.append("")
        kept_lines = _filter_verbatim.collapse_blank_runs(kept_lines)

        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text("\n".join(kept_lines).rstrip() + "\n", encoding="utf-8")

        kept_line_count = sum(1 for line in kept_lines if line.strip())
        percent_removed = (
            100.0 * (1 - kept_line_count / raw_line_count) if raw_line_count else 0.0
        )

        pages_kept = len(pages) - pages_dropped_whole
        message = spec_message
        if pages_dropped_whole:
            drop_note = f"{pages_dropped_whole} página(s) descartada(s) inteira(s) (anexo/contrato social)"
            message = f"{message}; {drop_note}" if message else drop_note

        return ExtractionResult(
            status="extracted",
            extractor_version=self.extractor_version,
            route=self.name,
            markdown_path=out_path,
            pages_total=page_count,
            pages_kept=pages_kept,
            percent_removed=round(percent_removed, 1),
            message=message,
        )

    def _spec_cache_dir(self, out_path: Path) -> Path:
        if self._spec_cache_dir_override is not None:
            return self._spec_cache_dir_override
        # `out_path` is `<output_dir>/markdown/<sha256>__<extractor_version>.md`
        # (see executor.py's `_extract`) — a route is never handed
        # `output_dir` directly per the extraction-route contract, so this
        # derives the sibling `llm_specs/` directory from the one path
        # this method does receive. See module docstring, "Two-tier cache".
        return out_path.parent.parent / "llm_specs"

    def _get_or_generate_spec(self, raw_text: str, out_path: Path) -> tuple[dict, str | None]:
        cache_dir = self._spec_cache_dir(out_path)
        cache_key = _spec_cache_key(raw_text, self.model_id)
        cache_path = cache_dir / f"{cache_key}.json"

        if cache_path.exists():
            cached = json.loads(cache_path.read_text(encoding="utf-8"))
            return cached["spec"], f"spec LLM em cache ({cached['model_id']})"

        generate_fn = self._generate_fn or make_bedrock_generate_fn(self.model_id, self.region)
        try:
            result = generate_fn(raw_text)
            result.spec = _validate_spec(result.spec)  # never trust a GenerateFn blindly,
            # whether it's the real Bedrock-backed one or a test double —
            # see _validate_spec's own docstring.
        except Exception as exc:
            # LLM call failed or returned something we can't trust (see
            # SpecGenerationError/_validate_spec) — fall back to the
            # generic-only filter (no per-document spec) rather than
            # erroring the whole document out. This is this route's own
            # documented precedence decision between "use the LLM spec"
            # and "behave like pdf_text_generic.py" (see module docstring).
            empty_spec = {
                "drop_pages": [],
                "drop_line_literals": [],
                "drop_line_contains": [],
                "strip_trailing_rubric_tokens": [],
                "notes": "",
            }
            return empty_spec, f"geração de spec via LLM falhou, usando filtro genérico: {exc}"

        cost_usd = estimate_cost_usd(result.model_id, result.input_tokens, result.output_tokens)
        cache_dir.mkdir(parents=True, exist_ok=True)
        cache_path.write_text(
            json.dumps(
                {
                    "spec": result.spec,
                    "model_id": result.model_id,
                    "region": result.region,
                    "prompt_version": PROMPT_VERSION,
                    "input_tokens": result.input_tokens,
                    "output_tokens": result.output_tokens,
                    "cost_usd": cost_usd,
                    "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                },
                ensure_ascii=False,
                indent=2,
            ),
            encoding="utf-8",
        )
        message = (
            f"spec gerada via LLM ({result.model_id}, "
            f"{result.input_tokens}+{result.output_tokens} tokens"
            + (f", ~US${cost_usd:.4f}" if cost_usd is not None else "")
            + ")"
        )
        return result.spec, message
